---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: finance_system
  tags:
    - events
spec:
  owner: user2
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: finance_database
  description: "Event Data"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/database.yaml"
spec:
  type: database
  owner: user2
  system: finance_system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: finance_events_s3
  description: "finance events S3 Bucket"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/s3-bucket.yaml"
spec:
  type: storage
  owner: user2
  system: finance_system
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: finance_events_api
  description: "Get finance Events API"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-grpc-api.yaml"
spec:
  type: grpc
  lifecycle: production
  owner: user2
  system: finance_system
  definition: |
    syntax = "proto3";
    package myorg.mygrpcapi;
    message MyRequest {
      string query = 1;
    }
    message MyResponse {
      string result = 1;
    }
    service MyGrpcApi {
      rpc MyMethod (MyRequest) returns (MyResponse);
    }
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: finance_backend
  description: "finance Events Backend Service"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-backend.yaml"
spec:
  type: service
  lifecycle: production
  owner: user2
  system: finance_system
  dependsOn:
    - resource:finance_database
    - resource:finance_events_s3
  providesApis:
    - events_api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: finance_frontend
  description: "Events Frontend Service"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-frontend.yaml"
spec:
  type: service
  lifecycle: production
  owner: user2
  system: finance_system
  consumesApis:
    - finance_events_api