---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecommerce_backend
  description: "ecommerce backend"
  tags:
    - ecommerce
    - backend
  annotations:
    backstage.io/managed-by-location: url:https://github.com/my-org/my-repo/blob/master/my-backend.yaml
spec:
  type: service
  lifecycle: production
  owner: user2
  system: ecommerce_system
  dependsOn:
    - resource:ecommerce_database
    - resource:ecommerce_s3
  consumesApis:
    - checkout_api
    - payments_api
    - ads_api
    - cart_api
    - catalog_api
    - shipping_api
    - email_api
    - sso_api
    - customerweb_api    
  providesApis:
    - ecommerce_api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecommerce_web
  description: "ecommerce web"
  tags:
    - ecommerce
    - frontend  
  annotations:
    backstage.io/managed-by-location: url:https://github.com/my-org/my-repo/blob/master/my-frontend.yaml
spec:
  type: service
  lifecycle: production
  owner: user2
  system: ecommerce_system
  consumesApis:
    - ecommerce_api
