---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: training_system
  tags:
    - events
spec:
  owner: user4
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: training_database
  description: "Training Database"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/database.yaml"
spec:
  type: database
  owner: user4
  system: training_system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: training_s3
  description: "training S3 Bucket"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/s3-bucket.yaml"
spec:
  type: storage
  owner: user4
  system: training_system
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: training_events_api
  description: "Get training Events API"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-grpc-api.yaml"
spec:
  type: grpc
  lifecycle: production
  owner: user4
  system: training_system
  definition: |
    syntax = "proto3";
    package myorg.mygrpcapi;
    message MyRequest {
      string query = 1;
    }
    message MyResponse {
      string result = 1;
    }
    service MyGrpcApi {
      rpc MyMethod (MyRequest) returns (MyResponse);
    }
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: training_backend
  description: "training Events Backend Service"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-backend.yaml"
spec:
  type: service
  lifecycle: production
  owner: user4
  system: training_system
  dependsOn:
    - resource:training_database
    - resource:training_events_s3
  providesApis:
    - events_api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: training_frontend
  description: "Events Frontend Service"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-frontend.yaml"
spec:
  type: service
  lifecycle: production
  owner: user4
  system: training_system
  consumesApis:
    - training_events_api